[package]
name = "sat"
version = "0.1.0"   
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde-wasm-bindgen = "0.5"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 3

